# Trabalho 01 - tabela Hash
 
all: trab
 
trab: main.o hash.o lista.o
    gcc -o trab main.o hash.o lista.o
 
main.o: main.c hash.h lista.h
    gcc -o main.o main.c -c -W -Wall -ansi -pedantic
 
lista.o: lista.c lista.h
    gcc -o lista.o lista.c -c -W -Wall -ansi -pedantic

hash.o: hash.c hash.h
    gcc -o hash.o hash.c -c -W -Wall -ansi -pedantic
 
clean:
    rm -rf *.o *~ trab